# Generated by Django 4.0.6 on 2022-07-14 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Electricitymeter',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('serialnumber', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Серийный номер')),
                ('verificationdate', models.DateField(blank=True, verbose_name='Дата поверки')),
                ('ratio_transform', models.PositiveSmallIntegerField(default=1, verbose_name='Коэффициент трансформации')),
                ('ratio_loss', models.PositiveSmallIntegerField(default=1.2, verbose_name='Коэффициент потерь')),
            ],
            options={
                'verbose_name': 'Счетчик электроэнергии',
                'verbose_name_plural': 'Счетчики электроэнергии',
                'ordering': ['-serialnumber'],
            },
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название арендатора')),
                ('iswater', models.BooleanField(default=False, verbose_name='Есть вода?')),
                ('tarifofwater', models.PositiveSmallIntegerField(default=9, verbose_name='Тариф вода')),
                ('iselectricity', models.BooleanField(default=True, verbose_name='Есть электроэнергия?')),
                ('tarifofelectricity', models.PositiveSmallIntegerField(default=11.8, verbose_name='Тариф за электроэнергию')),
                ('dateofrent', models.DateField(verbose_name='Дата въезда арендатора')),
                ('electricitymeter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roomsmeters.electricitymeter', verbose_name='Счетчик электроэнергии')),
            ],
            options={
                'verbose_name': 'Арендатор',
                'verbose_name_plural': 'Арендаторы',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Watermeter',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('serialnumber', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Серийный номер')),
                ('verificationdate', models.DateField(blank=True, verbose_name='Дата поверки')),
            ],
            options={
                'verbose_name': 'Счетчик воды',
                'verbose_name_plural': 'Счетчики воды',
                'ordering': ['-serialnumber'],
            },
        ),
        migrations.CreateModel(
            name='Waterdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datedata', models.DateField(auto_now=True, verbose_name='Дата снятия показаний')),
                ('consumption', models.PositiveSmallIntegerField(verbose_name='Текущее показание')),
                ('serialnumber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roomsmeters.watermeter', verbose_name='Серийный номер')),
            ],
            options={
                'verbose_name': 'Показание счетчика вода',
                'verbose_name_plural': 'Показания счетчиков воды',
                'ordering': ['-serialnumber'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Номер(название) помещения')),
                ('roomsquare', models.PositiveSmallIntegerField(verbose_name='Площадь помещения')),
                ('building', models.CharField(max_length=10, verbose_name='Корпус')),
                ('floor', models.CharField(max_length=10, verbose_name='Этаж')),
                ('renter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roomsmeters.renter', verbose_name='Арендатор')),
            ],
            options={
                'verbose_name': 'Помещение',
                'verbose_name_plural': 'Помещения',
                'ordering': ['-name'],
            },
        ),
        migrations.AddField(
            model_name='renter',
            name='watermeter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roomsmeters.watermeter', verbose_name='Счетчик воды'),
        ),
        migrations.CreateModel(
            name='Electricitydate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datedata', models.DateField(verbose_name='Дата снятия показаний')),
                ('consumption', models.PositiveSmallIntegerField(verbose_name='Текущие показание')),
                ('serialnumber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roomsmeters.electricitymeter', verbose_name='Серийный номер')),
            ],
            options={
                'verbose_name': 'Показание счетчика электроэнергии',
                'verbose_name_plural': 'Показания счетчиков электроэнергии',
                'ordering': ['-serialnumber'],
            },
        ),
    ]
