# Generated by Django 4.0.6 on 2022-07-14 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Electricitymeter',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('serialnumber', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('verificationdate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('iswater', models.BooleanField(default=False)),
                ('iselectricity', models.BooleanField(default=True)),
                ('electricitymeter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roomsmeters.electricitymeter')),
            ],
        ),
        migrations.CreateModel(
            name='Watermeter',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('serialnumber', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('verificationdate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Waterdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datedata', models.DateField(auto_now=True)),
                ('consumption', models.SmallIntegerField()),
                ('serialnumber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roomsmeters.watermeter')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roomsquare', models.SmallIntegerField()),
                ('building', models.CharField(max_length=10)),
                ('floor', models.CharField(max_length=10)),
                ('renter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roomsmeters.renter')),
            ],
        ),
        migrations.AddField(
            model_name='renter',
            name='watermeter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roomsmeters.watermeter'),
        ),
        migrations.CreateModel(
            name='Electricitydate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datedata', models.DateField(auto_now=True)),
                ('consumption', models.SmallIntegerField()),
                ('serialnumber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roomsmeters.electricitymeter')),
            ],
        ),
    ]
