# Generated by Django 4.0.6 on 2022-07-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomsmeters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricitymeter',
            options={'ordering': ['-serialnumber'], 'verbose_name': 'Счетчик электроэнергии', 'verbose_name_plural': 'Счетчики электроэнергии'},
        ),
        migrations.AlterModelOptions(
            name='renter',
            options={'ordering': ['-name'], 'verbose_name': 'Арендатор', 'verbose_name_plural': 'Арендаторы'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-name'], 'verbose_name': 'Помещение', 'verbose_name_plural': 'Помещения'},
        ),
        migrations.AlterModelOptions(
            name='watermeter',
            options={'ordering': ['-serialnumber'], 'verbose_name': 'Счетчик воды', 'verbose_name_plural': 'Счетчики воды'},
        ),
        migrations.AlterField(
            model_name='electricitydate',
            name='consumption',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomsquare',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='waterdate',
            name='consumption',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
