# Generated by Django 4.0.6 on 2022-07-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomsmeters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterdate',
            name='datedata',
            field=models.DateField(verbose_name='Дата снятия показаний'),
        ),
    ]
