# Generated by Django 4.0.6 on 2022-07-14 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomsmeters', '0002_alter_waterdate_datedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='renter',
        ),
        migrations.CreateModel(
            name='Rentaroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datestart', models.DateField(verbose_name='Дата начала аренды')),
                ('dateend', models.DateField(verbose_name='Дата окончания аренды')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomsmeters.renter', verbose_name='Название арендатора')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomsmeters.room', verbose_name='Помещение, которое снял арендатор')),
            ],
            options={
                'verbose_name': 'Какое помещение арендовано и кем',
                'verbose_name_plural': 'Какие помещения арендованы и кем',
                'ordering': ['-room'],
            },
        ),
    ]
