# Generated by Django 4.0.6 on 2022-07-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomsmeters', '0002_alter_electricitymeter_options_alter_renter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricitymeter',
            name='ratio_loss',
            field=models.PositiveSmallIntegerField(default=1.2),
        ),
        migrations.AddField(
            model_name='electricitymeter',
            name='ratio_transform',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='renter',
            name='tarifofelectricity',
            field=models.PositiveSmallIntegerField(default=11.8),
        ),
        migrations.AddField(
            model_name='renter',
            name='tarifofwater',
            field=models.PositiveSmallIntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='electricitymeter',
            name='verificationdate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='watermeter',
            name='verificationdate',
            field=models.DateField(blank=True),
        ),
    ]
