# Generated by Django 4.0.6 on 2022-07-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomsmeters', '0003_remove_room_renter_rentaroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentaroom',
            name='dateend',
            field=models.DateField(blank=True, verbose_name='Дата окончания аренды'),
        ),
    ]
