# Generated by Django 4.0.6 on 2022-07-14 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomsmeters', '0003_electricitymeter_ratio_loss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricitydate',
            name='consumption',
            field=models.PositiveSmallIntegerField(verbose_name='Текущие показание'),
        ),
        migrations.AlterField(
            model_name='electricitydate',
            name='datedata',
            field=models.DateField(verbose_name='Дата снятия показаний'),
        ),
        migrations.AlterField(
            model_name='electricitydate',
            name='serialnumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roomsmeters.electricitymeter', verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='electricitymeter',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='electricitymeter',
            name='ratio_loss',
            field=models.PositiveSmallIntegerField(default=1.2, verbose_name='Коэффициент потерь'),
        ),
        migrations.AlterField(
            model_name='electricitymeter',
            name='ratio_transform',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Коэффициент трансформации'),
        ),
        migrations.AlterField(
            model_name='electricitymeter',
            name='serialnumber',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='electricitymeter',
            name='verificationdate',
            field=models.DateField(blank=True, verbose_name='Дата поверки'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='electricitymeter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roomsmeters.electricitymeter', verbose_name='Счетчик электроэнергии'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='iselectricity',
            field=models.BooleanField(default=True, verbose_name='Есть электроэнергия?'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='iswater',
            field=models.BooleanField(default=False, verbose_name='Есть вода?'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название арендатора'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='tarifofelectricity',
            field=models.PositiveSmallIntegerField(default=11.8, verbose_name='Тариф за электроэнергию'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='tarifofwater',
            field=models.PositiveSmallIntegerField(default=9, verbose_name='Тариф вода'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='watermeter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roomsmeters.watermeter', verbose_name='Счетчик воды'),
        ),
        migrations.AlterField(
            model_name='room',
            name='building',
            field=models.CharField(max_length=10, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.CharField(max_length=10, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Номер(название) помещения'),
        ),
        migrations.AlterField(
            model_name='room',
            name='renter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roomsmeters.renter', verbose_name='Арендатор'),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomsquare',
            field=models.PositiveSmallIntegerField(verbose_name='Площадь помещения'),
        ),
        migrations.AlterField(
            model_name='waterdate',
            name='consumption',
            field=models.PositiveSmallIntegerField(verbose_name='Текущее показание'),
        ),
        migrations.AlterField(
            model_name='waterdate',
            name='datedata',
            field=models.DateField(auto_now=True, verbose_name='Дата снятия показаний'),
        ),
        migrations.AlterField(
            model_name='waterdate',
            name='serialnumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roomsmeters.watermeter', verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='watermeter',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='watermeter',
            name='serialnumber',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='watermeter',
            name='verificationdate',
            field=models.DateField(blank=True, verbose_name='Дата поверки'),
        ),
    ]
