# Generated by Django 4.0.6 on 2022-07-14 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomsmeters', '0004_alter_electricitydate_consumption_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waterdate',
            options={'ordering': ['-serialnumber'], 'verbose_name': 'Показание', 'verbose_name_plural': 'Показания'},
        ),
    ]
