# Generated by Django 4.0.6 on 2022-07-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomsmeters', '0004_alter_rentaroom_dateend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricitymeter',
            name='serialnumber',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название арендатора'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Номер(название) помещения'),
        ),
        migrations.AlterField(
            model_name='watermeter',
            name='serialnumber',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='Серийный номер'),
        ),
    ]
