# Generated by Django 4.0.6 on 2022-07-14 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomsmeters', '0005_alter_electricitymeter_serialnumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название Арендодателя')),
            ],
            options={
                'verbose_name': 'Арендодатель',
                'verbose_name_plural': 'Арендодатели',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Spotelectr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2, unique=True, verbose_name='Название участка')),
            ],
        ),
        migrations.CreateModel(
            name='Spotwater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2, unique=True, verbose_name='Название участка')),
            ],
        ),
        migrations.RemoveField(
            model_name='renter',
            name='dateofrent',
        ),
        migrations.RemoveField(
            model_name='renter',
            name='electricitymeter',
        ),
        migrations.RemoveField(
            model_name='renter',
            name='iselectricity',
        ),
        migrations.RemoveField(
            model_name='renter',
            name='iswater',
        ),
        migrations.RemoveField(
            model_name='renter',
            name='tarifofelectricity',
        ),
        migrations.RemoveField(
            model_name='renter',
            name='tarifofwater',
        ),
        migrations.RemoveField(
            model_name='renter',
            name='watermeter',
        ),
        migrations.AddField(
            model_name='rentaroom',
            name='electricitymeter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roomsmeters.electricitymeter', verbose_name='Счетчик электроэнергии'),
        ),
        migrations.AddField(
            model_name='rentaroom',
            name='iselectricity',
            field=models.BooleanField(default=True, verbose_name='Есть электроэнергия?'),
        ),
        migrations.AddField(
            model_name='rentaroom',
            name='iswater',
            field=models.BooleanField(default=False, verbose_name='Есть вода?'),
        ),
        migrations.AddField(
            model_name='rentaroom',
            name='tarifofelectricity',
            field=models.PositiveSmallIntegerField(default=11.8, verbose_name='Тариф за электроэнергию'),
        ),
        migrations.AddField(
            model_name='rentaroom',
            name='tarifofwater',
            field=models.PositiveSmallIntegerField(default=9, verbose_name='Тариф вода'),
        ),
        migrations.AddField(
            model_name='rentaroom',
            name='watermeter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roomsmeters.watermeter', verbose_name='Счетчик воды'),
        ),
        migrations.AlterField(
            model_name='rentaroom',
            name='datestart',
            field=models.DateField(verbose_name='Дата начала аренды или изменение условий'),
        ),
        migrations.AddField(
            model_name='rentaroom',
            name='lessor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='roomsmeters.lessor', verbose_name='Название арендодателя'),
        ),
        migrations.AddField(
            model_name='rentaroom',
            name='spotelectr',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='roomsmeters.spotelectr', verbose_name='Название участка для Электроэнергии'),
        ),
        migrations.AddField(
            model_name='rentaroom',
            name='spotwater',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='roomsmeters.spotwater', verbose_name='Название участка для воды'),
        ),
    ]
