# Generated by Django 4.0.6 on 2022-07-14 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomsmeters', '0005_alter_waterdate_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricitydate',
            options={'ordering': ['-serialnumber'], 'verbose_name': 'Показание счетчика электроэнергии', 'verbose_name_plural': 'Показания счетчиков электроэнергии'},
        ),
        migrations.AlterModelOptions(
            name='waterdate',
            options={'ordering': ['-serialnumber'], 'verbose_name': 'Показание счетчика вода', 'verbose_name_plural': 'Показания счетчиков воды'},
        ),
    ]
