# Generated by Django 4.0.6 on 2022-07-14 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomsmeters', '0006_lessor_spotelectr_spotwater_remove_renter_dateofrent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spotelectr',
            options={'ordering': ['-name'], 'verbose_name': 'Участок по электроэнергии', 'verbose_name_plural': 'Участки по электроэнергии'},
        ),
        migrations.AlterModelOptions(
            name='spotwater',
            options={'ordering': ['-name'], 'verbose_name': 'Участок по воде', 'verbose_name_plural': 'Участки по воде'},
        ),
    ]
