# Generated by Django 4.0.6 on 2022-07-14 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomsmeters', '0008_alter_electricitymeter_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricitymeter',
            options={'ordering': ['-serialnumber'], 'verbose_name': 'Счетчик электроэнергии', 'verbose_name_plural': 'Счетчики электроэнергии'},
        ),
        migrations.RenameField(
            model_name='electricitymeter',
            old_name='nameel',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='electricitymeter',
            old_name='ratio_lossel',
            new_name='ratio_loss',
        ),
        migrations.RenameField(
            model_name='electricitymeter',
            old_name='ratio_transformel',
            new_name='ratio_transform',
        ),
        migrations.RenameField(
            model_name='electricitymeter',
            old_name='serialnumberel',
            new_name='serialnumber',
        ),
        migrations.RenameField(
            model_name='electricitymeter',
            old_name='verificationdateel',
            new_name='verificationdate',
        ),
    ]
