# Generated by Django 4.0.6 on 2022-07-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomsmeters', '0009_alter_electricitymeter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricitymeter',
            name='ratio_loss',
            field=models.FloatField(default=1.2, verbose_name='Коэффициент потерь'),
        ),
    ]
