# Generated by Django 4.0.6 on 2022-07-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomsmeters', '0010_alter_electricitymeter_ratio_loss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricitydate',
            name='consumption',
            field=models.PositiveIntegerField(verbose_name='Текущие показание'),
        ),
    ]
