# Generated by Django 4.0.6 on 2022-07-14 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomsmeters', '0011_alter_electricitydate_consumption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricitydate',
            options={'ordering': ['-datedata'], 'verbose_name': 'Показание счетчика электроэнергии', 'verbose_name_plural': 'Показания счетчиков электроэнергии'},
        ),
    ]
