# Generated by Django 4.0.6 on 2022-07-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomsmeters', '0012_alter_electricitydate_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentaroom',
            name='tarifofelectricity',
            field=models.FloatField(default=11.8, verbose_name='Тариф за электроэнергию'),
        ),
        migrations.AlterField(
            model_name='rentaroom',
            name='tarifofwater',
            field=models.FloatField(default=9, verbose_name='Тариф вода'),
        ),
    ]
