# Generated by Django 4.0.6 on 2022-07-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomsmeters', '0013_alter_rentaroom_tarifofelectricity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentaroom',
            name='dateend',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания аренды'),
        ),
    ]
