# Generated by Django 4.0.6 on 2022-07-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomsmeters', '0015_electricitydate_difference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watermeter',
            name='verificationdate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата поверки'),
        ),
    ]
