# Generated by Django 4.0.6 on 2022-07-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomsmeters', '0016_alter_watermeter_verificationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watermeter',
            name='verificationdate',
            field=models.DateField(blank=True, default='', null=True, verbose_name='Дата поверки'),
        ),
    ]
