# Generated by Django 4.0.6 on 2022-07-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomsmeters', '0017_alter_watermeter_verificationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentaroom',
            name='isfree',
            field=models.BooleanField(default=True, verbose_name='Помещеине свободно?'),
        ),
    ]
