# Generated by Django 4.0.6 on 2022-07-21 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomsmeters', '0018_rentaroom_isfree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricitydate',
            name='difference',
        ),
        migrations.RemoveField(
            model_name='electricitydate',
            name='suminrubles',
        ),
        migrations.RemoveField(
            model_name='waterdate',
            name='difference',
        ),
        migrations.RemoveField(
            model_name='waterdate',
            name='suminrubles',
        ),
    ]
